import 'dotenv/config';
import * as fs from 'fs';
import * as path from 'path';
import { NestFactory } from '@nestjs/core';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { AppModule } from '../src/app.module';

/**
 * Script to dump Swagger / OpenAPI documentation generated by NestJS.
 * Writes JSON output and ensures output directory exists.
 */
async function dumpOpenApi() {
  process.env.NODE_ENV = 'test';
  const app = await NestFactory.create(AppModule, { logger: false });
  app.setGlobalPrefix('v1');

  const swaggerConfig = new DocumentBuilder()
    .setTitle('LuxeKnox API')
    .setDescription('LuxeKnox backend spine and core platform services API')
    .setVersion('0.1.0')
    .addBearerAuth(
      {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'Opaque (gk_at_*)',
        description: 'Provide your opaque access token prefixed with gk_at_',
      },
      'bearer',
    )
    .build();

  const document = SwaggerModule.createDocument(app, swaggerConfig);

  const outDir = path.resolve(__dirname, '../../../docs/openapi');
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  const jsonPath = path.join(outDir, 'v1.json');
  fs.writeFileSync(jsonPath, JSON.stringify(document, null, 2), 'utf-8');
  console.log(`[OpenAPI] Dumped OpenAPI spec to: ${jsonPath}`);
  console.log(`[OpenAPI] Endpoints found: ${Object.keys(document.paths || {}).length}`);

  await app.close();
}

dumpOpenApi().catch((err) => {
  console.error('[OpenAPI] Failed to dump OpenAPI:', err);
  process.exitCode = 1;
});
