// Curated additions popular in Indian gyms / functional training that free-exercise-db may lack.
// English names only. Entries whose name already exists in the base dataset are skipped.
const steps = (...s) => s.map((t, i) => `${i + 1}. ${t}`).join('\n');

export const extras = [
  {
    name: 'Sun Salutation',
    primary_muscle_group: 'Shoulders',
    secondary_muscles: ['Chest', 'Hamstrings', 'Quadriceps', 'Lower Back', 'Abdominals'],
    equipment_needed: 'Bodyweight',
    instructions: steps(
      'Stand tall with feet together and palms pressed at the chest.',
      'Inhale, raise both arms overhead and arch back slightly.',
      'Exhale, hinge forward at the hips and place hands beside your feet.',
      'Inhale, step one leg back into a low lunge and look forward.',
      'Exhale, step the other leg back into a plank position.',
      'Lower the chest and knees to the floor, then inhale into a cobra or upward-facing dog.',
      'Exhale, lift the hips into a downward-facing dog and hold for a breath.',
      'Step forward into a lunge, fold over your legs, then rise back to standing with arms overhead.',
    ),
    difficulty_level: 'Beginner',
    category: 'Stretching',
    mechanic: 'Compound',
    force: null,
  },
  {
    name: 'Hindu Push-Up',
    primary_muscle_group: 'Chest',
    secondary_muscles: ['Shoulders', 'Triceps', 'Lower Back', 'Abdominals'],
    equipment_needed: 'Bodyweight',
    instructions: steps(
      'Start in a downward-dog position, hips high, hands and feet shoulder-width apart.',
      'Bend the elbows and swoop the chest forward and down, close to the floor.',
      'Continue the arc, pushing the hips down and chest up into an upward-dog position.',
      'Reverse the movement, sending the hips back up to the starting position.',
    ),
    difficulty_level: 'Intermediate',
    category: 'Strength',
    mechanic: 'Compound',
    force: 'Push',
  },
  {
    name: 'Hindu Squat',
    primary_muscle_group: 'Quadriceps',
    secondary_muscles: ['Glutes', 'Hamstrings', 'Calves'],
    equipment_needed: 'Bodyweight',
    instructions: steps(
      'Stand with feet shoulder-width apart and arms extended in front of you.',
      'Swing the arms back as you squat, rising onto the balls of your feet with heels lifted.',
      'Drop the hips toward your heels while keeping the chest up.',
      'Swing the arms forward and drive through the toes to stand up.',
    ),
    difficulty_level: 'Beginner',
    category: 'Strength',
    mechanic: 'Compound',
    force: 'Push',
  },
  {
    name: 'Mace 360',
    primary_muscle_group: 'Shoulders',
    secondary_muscles: ['Forearms', 'Lats', 'Abdominals', 'Triceps'],
    equipment_needed: 'Mace',
    instructions: steps(
      'Stand with feet wider than shoulder-width and hold the mace handle with both hands.',
      'Raise the mace vertically in front of you, then let the head drop behind one shoulder.',
      'Swing it around the back of the head and across to the other shoulder in a full circle.',
      'Keep the core braced and use the hips to drive the rotation, then repeat in the opposite direction.',
    ),
    difficulty_level: 'Intermediate',
    category: 'Strength',
    mechanic: 'Compound',
    force: 'Pull',
  },
  {
    name: 'Club Swing',
    primary_muscle_group: 'Shoulders',
    secondary_muscles: ['Forearms', 'Lats', 'Abdominals'],
    equipment_needed: 'Club',
    instructions: steps(
      'Stand with feet shoulder-width apart, holding a club in each hand or one club with both hands.',
      'Swing the club back over the shoulder in a controlled arc.',
      'Bring it forward and across the body, letting the hips and torso rotate.',
      'Maintain a steady rhythm and switch directions after each set.',
    ),
    difficulty_level: 'Intermediate',
    category: 'Strength',
    mechanic: 'Compound',
    force: 'Pull',
  },
  {
    name: 'Jump Rope',
    primary_muscle_group: 'Calves',
    secondary_muscles: ['Shoulders', 'Forearms', 'Quadriceps'],
    equipment_needed: 'Jump Rope',
    instructions: steps(
      'Hold the handles at hip height with elbows close to your sides.',
      'Swing the rope over your head using the wrists, not the arms.',
      'Jump just high enough to clear the rope, landing softly on the balls of the feet.',
      'Keep a steady rhythm and an upright posture.',
    ),
    difficulty_level: 'Beginner',
    category: 'Cardio',
    mechanic: 'Compound',
    force: null,
  },
  {
    name: 'Treadmill Running',
    primary_muscle_group: 'Quadriceps',
    secondary_muscles: ['Hamstrings', 'Calves', 'Glutes'],
    equipment_needed: 'Treadmill',
    instructions: steps(
      'Start with a 3-5 minute walk to warm up.',
      'Increase the speed to a comfortable running pace, holding the handrails only if needed for balance.',
      'Keep the torso upright, land midfoot and keep arms swinging at 90 degrees.',
      'Cool down with a 3-5 minute walk.',
    ),
    difficulty_level: 'Beginner',
    category: 'Cardio',
    mechanic: 'Compound',
    force: null,
  },
  {
    name: 'Stationary Bike',
    primary_muscle_group: 'Quadriceps',
    secondary_muscles: ['Hamstrings', 'Calves', 'Glutes'],
    equipment_needed: 'Exercise Bike',
    instructions: steps(
      'Adjust the seat so your knee is slightly bent at the bottom of the pedal stroke.',
      'Sit tall with hands on the handlebars and pedal at a steady cadence.',
      'Adjust resistance to match your target intensity.',
    ),
    difficulty_level: 'Beginner',
    category: 'Cardio',
    mechanic: 'Compound',
    force: null,
  },
  {
    name: 'Rowing Machine',
    primary_muscle_group: 'Lats',
    secondary_muscles: ['Middle Back', 'Biceps', 'Quadriceps', 'Hamstrings', 'Glutes'],
    equipment_needed: 'Rowing Machine',
    instructions: steps(
      'Sit with feet strapped in and grasp the handle with arms straight.',
      'Drive with the legs first, then lean back slightly and pull the handle to the lower ribs.',
      'Extend the arms, hinge the torso forward, then bend the knees to return to the start.',
    ),
    difficulty_level: 'Beginner',
    category: 'Cardio',
    mechanic: 'Compound',
    force: 'Pull',
  },
  {
    name: 'Battle Rope Waves',
    primary_muscle_group: 'Shoulders',
    secondary_muscles: ['Forearms', 'Abdominals', 'Lats'],
    equipment_needed: 'Battle Ropes',
    instructions: steps(
      'Hold one end of the rope in each hand with feet shoulder-width apart and knees slightly bent.',
      'Alternate raising and lowering each arm explosively to create waves along the rope.',
      'Keep the core tight and maintain a steady pace for the set duration.',
    ),
    difficulty_level: 'Intermediate',
    category: 'Cardio',
    mechanic: 'Compound',
    force: 'Pull',
  },
  {
    name: 'Kettlebell Goblet Squat',
    primary_muscle_group: 'Quadriceps',
    secondary_muscles: ['Glutes', 'Hamstrings', 'Abdominals'],
    equipment_needed: 'Kettlebells',
    instructions: steps(
      'Hold a kettlebell by the horns against your chest with elbows pointing down.',
      'Squat down, keeping the chest tall and knees tracking over the toes.',
      'Drive through the heels to stand back up.',
    ),
    difficulty_level: 'Beginner',
    category: 'Strength',
    mechanic: 'Compound',
    force: 'Push',
  },
];
